AWSTemplateFormatVersion: "2010-09-09"
Description: AWS WAF Cloudformation template
Parameters:
  WebACLName:
    Type: String
    Description: "WebACL Name"
  Scope:
    Type: String
    Default: CLOUDFRONT
    AllowedValues:
    - CLOUDFRONT
    - REGIONAL
    Description: "CLOUDFRONT or REGIONAL"
Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub aws-waf-logs-${WebACLName}
      RetentionInDays: 30

  WebAcl:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub ${WebACLName}
      Scope: !Sub ${Scope}
      DefaultAction:
        Allow: {}
      Description: "Baseline and Rate-based rules"
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        SampledRequestsEnabled: true
        MetricName: !Sub ${WebACLName}
      Rules:
        - Name: AWS-AWSManagedRulesCommonRuleSet
          Priority: 0
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
              ExcludedRules:
                - Name: NoUserAgent_HEADER
                - Name: UserAgent_BadBots_HEADER
                - Name: SizeRestrictions_QUERYSTRING
                - Name: SizeRestrictions_Cookie_HEADER
                - Name: SizeRestrictions_BODY
                - Name: SizeRestrictions_URIPATH
                - Name: EC2MetaDataSSRF_BODY
                - Name: EC2MetaDataSSRF_COOKIE
                - Name: EC2MetaDataSSRF_URIPATH
                - Name: EC2MetaDataSSRF_QUERYARGUMENTS
                - Name: GenericLFI_QUERYARGUMENTS
                - Name: GenericLFI_URIPATH
                - Name: GenericLFI_BODY
                - Name: RestrictedExtensions_URIPATH
                - Name: RestrictedExtensions_QUERYARGUMENTS
                - Name: GenericRFI_QUERYARGUMENTS
                - Name: GenericRFI_BODY
                - Name: GenericRFI_URIPATH
                - Name: CrossSiteScripting_COOKIE
                - Name: CrossSiteScripting_QUERYARGUMENTS
                - Name: CrossSiteScripting_BODY
                - Name: CrossSiteScripting_URIPATH
          OverrideAction:
            None: {}
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            SampledRequestsEnabled: true
            MetricName: AWS-AWSManagedRulesCommonRuleSet
        - Name: "AWSManagedRulesKnownBadInputsRule"
          Priority: 1
          Statement:
            ManagedRuleGroupStatement:
              VendorName: "AWS"
              Name: "AWSManagedRulesKnownBadInputsRuleSet"
              ExcludedRules:
                - Name: ExploitablePaths_URIPATH
                - Name: Host_localhost_HEADER
                - Name: Log4JRCE
                - Name: PROPFIND_METHOD
                - Name: ExploitablePaths_URIPATH
                - Name: JavaDeserializationRCE_BODY
                - Name: JavaDeserializationRCE_URIPATH
                - Name: JavaDeserializationRCE_QUERYSTRING
                - Name: JavaDeserializationRCE_HEADER
          OverrideAction:
            None: {}
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: "AWSManagedRulesKnownBadInputsRuleSet"
            SampledRequestsEnabled: true
        - Name: "RateBasedRule"
          Action:
            Count: {}
          Priority: 2
          Statement:
            RateBasedStatement:
              AggregateKeyType: IP
              Limit: 100
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: "RateBasedRule"
            SampledRequestsEnabled: true
  LogConfig:
    Type: AWS::WAFv2::LoggingConfiguration
    Properties:
      ResourceArn: !GetAtt "WebAcl.Arn"
      LogDestinationConfigs:
        - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:aws-waf-logs-${WebACLName}
