AWSTemplateFormatVersion: "2010-09-09"
Description: AWS WAF Cloudformation template
Parameters:
  WebACLName:
    Type: String
    Description: "WebACL Name"
  Scope:
    Type: String
    Default: CLOUDFRONT
    AllowedValues:
    - CLOUDFRONT
    - REGIONAL
    Description: "CLOUDFRONT or REGIONAL"
Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub aws-waf-logs-${WebACLName}
      RetentionInDays: 30

  WebAcl:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub ${WebACLName}
      Scope: !Sub ${Scope}
      DefaultAction:
        Allow: {}
      Description: "Baseline and Rate-based rules"
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        SampledRequestsEnabled: true
        MetricName: !Sub ${WebACLName}
      Rules:
        - Name: AWS-AWSManagedRulesCommonRuleSet
          Priority: 0
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
              RuleActionOverrides:
              - ActionToUse:
                  Count: {}
                Name: NoUserAgent_HEADER
              - ActionToUse:
                  Count: {}
                Name: UserAgent_BadBots_HEADER
              - ActionToUse:
                  Count: {}
                Name: SizeRestrictions_QUERYSTRING
              - ActionToUse:
                  Count: {}
                Name: SizeRestrictions_Cookie_HEADER
              - ActionToUse:
                  Count: {}
                Name: SizeRestrictions_BODY
              - ActionToUse:
                  Count: {}
                Name: SizeRestrictions_URIPATH
              - ActionToUse:
                  Count: {}
                Name: EC2MetaDataSSRF_BODY
              - ActionToUse:
                  Count: {}
                Name: EC2MetaDataSSRF_COOKIE
              - ActionToUse:
                  Count: {}
                Name: EC2MetaDataSSRF_URIPATH
              - ActionToUse:
                  Count: {}
                Name: EC2MetaDataSSRF_QUERYARGUMENTS
              - ActionToUse:
                  Count: {}
                Name: GenericLFI_QUERYARGUMENTS
              - ActionToUse:
                  Count: {}
                Name: GenericLFI_URIPATH
              - ActionToUse:
                  Count: {}
                Name: GenericLFI_BODY
              - ActionToUse:
                  Count: {}
                Name: RestrictedExtensions_URIPATH
              - ActionToUse:
                  Count: {}
                Name: RestrictedExtensions_QUERYARGUMENTS
              - ActionToUse:
                  Count: {}
                Name: GenericRFI_QUERYARGUMENTS
              - ActionToUse:
                  Count: {}
                Name: GenericRFI_BODY
              - ActionToUse:
                  Count: {}
                Name: GenericRFI_URIPATH
              - ActionToUse:
                  Count: {}
                Name: CrossSiteScripting_COOKIE
              - ActionToUse:
                  Count: {}
                Name: CrossSiteScripting_QUERYARGUMENTS
              - ActionToUse:
                  Count: {}
                Name: CrossSiteScripting_BODY
              - ActionToUse:
                  Count: {}
                Name: CrossSiteScripting_URIPATH
              ExcludedRules: []
          OverrideAction:
            None: {}
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            SampledRequestsEnabled: true
            MetricName: AWS-AWSManagedRulesCommonRuleSet
        - Name: "AWS-AWSManagedRulesKnownBadInputsRuleSet"
          Priority: 1
          Statement:
            ManagedRuleGroupStatement:
              VendorName: "AWS"
              Name: "AWSManagedRulesKnownBadInputsRuleSet"
              RuleActionOverrides:
              - ActionToUse:
                  Count: {}
                Name: NoUserAgent_HEADER
              - ActionToUse:
                  Count: {}
                Name: ExploitablePaths_URIPATH
              - ActionToUse:
                  Count: {}
                Name: Host_localhost_HEADER
              - ActionToUse:
                  Count: {}
                Name: Log4JRCE_QUERYSTRING
              - ActionToUse:
                  Count: {}
                Name: Log4JRCE_BODY
              - ActionToUse:
                  Count: {}
                Name: Log4JRCE_URIPATH
              - ActionToUse:
                  Count: {}
                Name: Log4JRCE_HEADER
              - ActionToUse:
                  Count: {}
                Name: PROPFIND_METHOD
              - ActionToUse:
                  Count: {}
                Name: JavaDeserializationRCE_BODY
              - ActionToUse:
                  Count: {}
                Name: JavaDeserializationRCE_URIPATH
              - ActionToUse:
                  Count: {}
                Name: JavaDeserializationRCE_QUERYSTRING
              - ActionToUse:
                  Count: {}
                Name: JavaDeserializationRCE_HEADER
              ExcludedRules: []
          OverrideAction:
            None: {}
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: "AWS-AWSManagedRulesKnownBadInputsRuleSet"
            SampledRequestsEnabled: true
        - Name: "RateBasedRule"
          Action:
            Count: {}
          Priority: 2
          Statement:
            RateBasedStatement:
              AggregateKeyType: IP
              Limit: 100
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: "RateBasedRule"
            SampledRequestsEnabled: true
  LogConfig:
    Type: AWS::WAFv2::LoggingConfiguration
    Properties:
      ResourceArn: !GetAtt "WebAcl.Arn"
      LogDestinationConfigs:
        - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:aws-waf-logs-${WebACLName}
